---
apiVersion: v1
kind: List
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: receiver-app
    name: receiver-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: receiver-app:latest
    postCommit: {}
    resources: {}
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fuse7-java-openshift:1.3
      type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: receiver-app
